[package]
name = "ntlm-hash-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ntlmhash"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntlm-hash = "0.1.0"
