[package]
name = "ntlm-hash-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ntlmhash"
crate-type = ["cdylib"] # this is for macos, delete for linux based systems

[dependencies]
ntlm-hash = "0.1.0"
